### ISSUE TITLE
Docker env vars for accesses

### ISSUE THREAD

**Issue by HugoFerrant** [fclairamb/ftpserver#403]
I was looking for env vars to be used in the "accesses" part of the ftpserver.json, but couldn't find any. After looking at the Dockerfile, I think this is just not implemented at this time.
Am I right or did I miss something ? Are you planning on implementing this ?
I found 1 or 2 simple workarounds, I'll comment here if everything work, for future usages.

**Comment by HugoFerrant** [comment]
btw great work on this plug&play ftp server 🎉

**Comment by HugoFerrant** [comment]
here is my workaround :
I created a `ftpserver.json.template` file next to my `ftpserver.json`.
The template contains the contente expected to be found in `ftpserver.json`, except for the "env vars dependent" parts, which contains placeholders.
Then, in my `docker-compose.yml`, I added and `entrypoint` key in which I copy the template then do a good old `sed`to replace my placeholders with actual env vars values.

For my concrete example (using minio here but not) :

my `ftpserver.json.template` :
```json
{
  "version": 1,
  "accesses": [
    {
      "user": "FTP_USER",
      "pass": "FTP_PASSWORD",
      "fs": "s3",
      "params": {
        "endpoint": "http://minio:9000",
        "region": "us-east-1",
        "bucket": "MINIO_BUCKET_NAME",
        "access_key_id": "MINIO_USER_ACCESS_KEY",
        "secret_access_key": "MINIO_USER_SECRET_KEY",
        "path_style": "true"
      }
    }
  ],
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  }
}
```


my `docker-compose.yml` :
```yaml
  ftpserver:
    image: fclairamb/ftpserver
    volumes:
      - ./docker/ftpserver:/app
    ports:
      - '2121-2130:2121-2130'
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      cp /app/ftpserver.json.template /app/ftpserver.json;
      sed -i "s/FTP_USER/$FTP_USER/g" /app/ftpserver.json;
      sed -i "s/FTP_PASSWORD/$FTP_PASSWORD/g" /app/ftpserver.json;
      sed -i "s/MINIO_BUCKET_NAME/$MINIO_BUCKET_NAME/g" /app/ftpserver.json;
      sed -i "s/MINIO_USER_ACCESS_KEY/$MINIO_USER_ACCESS_KEY/g" /app/ftpserver.json;
      sed -i "s/MINIO_USER_SECRET_KEY/$MINIO_USER_SECRET_KEY/g" /app/ftpserver.json;
      /bin/ftpserver;
      "
```
