### ISSUE TITLE
curl works but doesn't any ftp client 

### ISSUE THREAD

**Issue by smirnoww** [fclairamb/ftpserver#925]
Hello!
I run ftpserver on my vps with docker-compose.yml:
```
version: '3.3'
services:
    ftpserver:
        ports:
            - '2121-2130:2121-2130'
        volumes:
            - /home/ftp/shared:/tmp
            - /home/ftp:/app
        image: fclairamb/ftpserver
```
I also add vps public ip .env file:
```
PUBLIC_HOST=45.67.57.2
```
file ftpserver.json has been created automatically
```
{
  "version": 1,
  "accesses": [
    {
      "user": "test",
      "pass": "test",
      "fs": "os",
      "params": {
        "basePath": "/tmp"
      }
    }
  ],
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  }
}
```
When I run command on my local computer (not vps) from wsl
```
curl ftp://test:test@smirnov.solutions:2121
```
I get list of files:
![image](https://user-images.githubusercontent.com/6284636/215275124-4cc6c30f-2b52-4480-9504-6ac1606c0fb7.png)

But if I try to connect with any ftp client, I get something like this:
![image](https://user-images.githubusercontent.com/6284636/215275042-dc0d6ffc-889e-4396-a9c4-11bb98c5da32.png)
